# Generated by Django 5.1.15 on 2026-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='Celery task UUID or RabbitMQ message ID', max_length=255)),
                ('task_name', models.CharField(db_index=True, help_text='Python task path or message type', max_length=255)),
                ('queue_name', models.CharField(db_index=True, default='teamflow.tasks', max_length=100)),
                ('routing_key', models.CharField(blank=True, default='tasks', max_length=100)),
                ('exchange', models.CharField(blank=True, default='teamflow', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw payload or serialized message body')),
                ('args', models.JSONField(blank=True, default=list, help_text='Positional arguments passed to task')),
                ('kwargs', models.JSONField(blank=True, default=dict, help_text='Keyword arguments passed to task')),
                ('exception_class', models.CharField(blank=True, max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('replayed', 'Replayed / Requeued'), ('purged', 'Purged / Discarded'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_replayed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dead Letter Message',
                'verbose_name_plural': 'Dead Letter Queue (DLQ)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dlq_status_created_idx'), models.Index(fields=['queue_name', 'status'], name='dlq_queue_status_idx')],
            },
        ),
    ]
