# Generated by Django 5.1.15 on 2026-09-18 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Domain event class or topic', max_length=100)),
                ('exchange', models.CharField(default='teamflow.events', help_text='AMQP topic exchange', max_length=100)),
                ('routing_key', models.CharField(default='events', help_text='AMQP routing key', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Serialized domain event payload')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Message headers (tracing IDs, metadata)')),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outbox Message',
                'verbose_name_plural': 'Transactional Outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_status_created_idx'), models.Index(fields=['event_type', 'status'], name='outbox_event_status_idx')],
            },
        ),
    ]
