# Generated by Django 5.1.15 on 2026-09-18 20:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_outboxmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='headers',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Message headers (tracing IDs, metadata)'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='payload',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Serialized domain event payload'),
        ),
    ]
