# Generated by Django 5.1.15 on 2026-08-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('pending', 'Pending Approval'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('tech_lead', 'Tech Lead'), ('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('devops', 'DevOps Engineer'), ('qa', 'QA Engineer'), ('designer', 'UI/UX Designer'), ('seo', 'SEO Specialist'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
