# Generated by Django 5.1.15 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bio_user_user_status_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ceo", "CEO"),
                    ("pm", "Product Manager"),
                    ("tech_lead", "Tech Lead"),
                    ("backend", "Backend Developer"),
                    ("frontend", "Frontend Developer"),
                    ("devops", "DevOps Engineer"),
                    ("qa", "QA Engineer"),
                    ("designer", "UI/UX Designer"),
                    ("seo", "SEO Specialist"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
