# Generated by Django 5.1.15 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_agent_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clerk_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
