# Generated by Django 5.1.15 on 2026-08-23 16:52

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0002_task_due_date_task_pr_url_task_qa_rejected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecutionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32)),
                ('graph_state', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('langfuse_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodebaseEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codebase_embeddings', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='projects.project')),
            ],
            options={
                'ordering': ['file_path', 'chunk_index'],
                'indexes': [models.Index(fields=['file_path'], name='agents_code_file_pa_61b84b_idx'), models.Index(fields=['project'], name='agents_code_project_6e208a_idx')],
            },
        ),
    ]
