# Generated by Django 5.1.15 on 2026-09-19 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentevent'),
        ('organizations', '0003_backfill_memberships'),
        ('tasks', '0004_comment_comment_task_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentexecutiontrace',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('release', 'Release')], default='release', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('branch', models.CharField(max_length=255)),
                ('head_sha', models.CharField(max_length=40)),
                ('repo', models.CharField(blank=True, default='', max_length=255)),
                ('pr_url', models.CharField(blank=True, default='', max_length=500)),
                ('engine', models.CharField(choices=[('graph', 'Graph'), ('chain', 'Chain')], default='graph', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_approvals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='organizations.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tasks.task')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='agents.agentexecutiontrace')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['organization', 'task', 'status'], name='agents_appr_org_task_stat_idx')],
            },
        ),
    ]
