# Generated by Django 5.1.15 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_repo",
            field=models.CharField(blank=True, default="Asta-Builds/TeamFlow", max_length=255),
        ),
    ]
