# Generated by Django 5.1 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_github_repo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github_repo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
