# Generated by Django 5.1.15 on 2026-09-17 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_backfill_memberships'),
        ('projects', '0003_alter_project_github_repo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='proj_org_stat_idx'),
        ),
    ]
