# Generated by Django 5.1.15 on 2026-09-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True, help_text='Slack Incoming Webhook URL (e.g. https://hooks.slack.com/services/...)', max_length=500)),
                ('bot_token', models.CharField(blank=True, help_text='Slack Bot User OAuth Token (xoxb-...)', max_length=255)),
                ('default_channel', models.CharField(default='#general', max_length=100)),
                ('devops_channel', models.CharField(default='#devops', max_length=100)),
                ('qa_channel', models.CharField(default='#qa', max_length=100)),
                ('seo_channel', models.CharField(default='#seo', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notify_on_ticket_assigned', models.BooleanField(default=True)),
                ('notify_on_deployment', models.BooleanField(default=True)),
                ('notify_on_qa_rejection', models.BooleanField(default=True)),
                ('notify_on_seo_drop', models.BooleanField(default=True)),
                ('notify_on_agent_response', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to='organizations.organization')),
            ],
        ),
    ]
