# Generated by Django 5.1.15 on 2026-09-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_githubintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubintegration',
            name='github_org',
            field=models.CharField(blank=True, default='', help_text='Default GitHub Organization or user login (e.g. organization-or-user)', max_length=100),
        ),
    ]
