apiVersion: v1
kind: ConfigMap
metadata:
  name: teamflow-config
  namespace: teamflow
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,https://teamflow.yourdomain.com"
  CSRF_TRUSTED_ORIGINS: "http://localhost:3000,https://teamflow.yourdomain.com"
  NEXT_PUBLIC_API_URL: "/api"
  PORT: "8000"
  FRONTEND_PORT: "3000"
  RABBITMQ_DEFAULT_USER: "teamflow"
  RABBITMQ_MANAGEMENT_URL: "http://teamflow-rabbitmq:15672"
