apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamflow-redis
  namespace: teamflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamflow-redis
  template:
    metadata:
      labels:
        app: teamflow-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: teamflow-redis
  namespace: teamflow
spec:
  type: ClusterIP
  selector:
    app: teamflow-redis
  ports:
    - port: 6379
      targetPort: 6379
