# Generated by Django 5.1.15 on 2026-08-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date_task_pr_url_task_qa_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contract_compliance_score',
            field=models.FloatField(default=0.0, help_text='Percentage of contract assertions independently validated by QA (0.0 to 100.0)'),
        ),
        migrations.AddField(
            model_name='task',
            name='validation_contract',
            field=models.JSONField(blank=True, default=list, help_text="Upfront independent assertions & invariants defining 'Done' for this task"),
        ),
    ]
