# Generated by Django 5.1.15 on 2026-08-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='load_time_ms',
            field=models.PositiveIntegerField(default=350),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='mobile_score',
            field=models.PositiveSmallIntegerField(default=95),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='performance_score',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='seo_score',
            field=models.PositiveSmallIntegerField(default=92),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100 overall audit score'),
        ),
    ]
